### ISSUE TITLE
Exception on input format with large / complex multi-polygon

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#285]
Exceptions in map reduce based query have been reported when using large multi-polygons (large as in large number of vertices)

**Comment by chrisbennight** [comment]
So I was able to duplicate an error that may be related.  It's just a basic java memory limit - based probably on the environmental settings for the iterators - at some point the geometries appear to get big enough that they exhaust it  Stack trace at bottom:

This is happening for me at values over 29,000 vertices in a polygon. (with default memory settings, etc.)

Here's the test I used for this: https://github.com/ngageoint/geowave/commit/e34e4709ba1a8975f60f76310eafd5ee3d14c449

Not sure what the best solution is
  * Document it as a limit
  * Optional / integrated simplify capability
  * Tile the query geometry into multiple smaller queries (ideally based on vertex density?)

?



```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.vividsolutions.jts.geom.impl.CoordinateArraySequence.<init>(CoordinateArraySequence.java:116)
	at com.vividsolutions.jts.geom.impl.CoordinateArraySequenceFactory.create(CoordinateArraySequenceFactory.java:91)
	at com.vividsolutions.jts.io.WKBReader.readCoordinateSequence(WKBReader.java:310)
	at com.vividsolutions.jts.io.WKBReader.readCoordinateSequenceRing(WKBReader.java:333)
	at com.vividsolutions.jts.io.WKBReader.readLinearRing(WKBReader.java:241)
	at com.vividsolutions.jts.io.WKBReader.readPolygon(WKBReader.java:252)
	at com.vividsolutions.jts.io.WKBReader.readGeometry(WKBReader.java:191)
	at com.vividsolutions.jts.io.WKBReader.read(WKBReader.java:152)
	at com.vividsolutions.jts.io.WKBReader.read(WKBReader.java:133)
	at mil.nga.giat.geowave.store.GeometryUtils.geometryFromBinary(GeometryUtils.java:198)
	at mil.nga.giat.geowave.store.filter.SpatialQueryFilter.fromBinary(SpatialQueryFilter.java:191)
	at mil.nga.giat.geowave.index.PersistenceUtils.fromBinary(PersistenceUtils.java:92)
	at mil.nga.giat.geowave.store.filter.DistributableFilterList.fromBinary(DistributableFilterList.java:58)
	at mil.nga.giat.geowave.index.PersistenceUtils.fromBinary(PersistenceUtils.java:92)
	at mil.nga.giat.geowave.accumulo.query.QueryFilterIterator.init(QueryFilterIterator.java:105)
	at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:253)
	at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:223)
	at org.apache.accumulo.core.client.mock.MockScannerBase.createFilter(MockScannerBase.java:108)
	at org.apache.accumulo.core.client.mock.MockBatchScanner.iterator(MockBatchScanner.java:63)
	at mil.nga.giat.geowave.accumulo.query.AccumuloFilteredIndexQuery.initIterator(AccumuloFilteredIndexQuery.java:115)
	at mil.nga.giat.geowave.accumulo.query.AccumuloFilteredIndexQuery.query(AccumuloFilteredIndexQuery.java:95)
	at mil.nga.giat.geowave.accumulo.AccumuloDataStore.query(AccumuloDataStore.java:1058)
	at mil.nga.giat.geowave.accumulo.AccumuloDataStore.query(AccumuloDataStore.java:1131)
	at mil.nga.giat.geowave.accumulo.AccumuloDataStore.query(AccumuloDataStore.java:1095)
	at mil.nga.giat.geowave.accumulo.query.AccumuloRangeQueryTest.largeQuery(AccumuloRangeQueryTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)


Process finished with exit code -1
```

**Comment by chrisbennight** [comment]
Using Jamm ( https://github.com/jbellis/jamm ) 29k vertices gives:
```
size: 40 bytes
retained size: 1276272 bytes
inner object count: 29011
```
for the polygon

couple that with the fact that you might get multiple instances of iterators per scan range, and I guess it could expand pretty large:
ref: http://apache-accumulo.1065345.n5.nabble.com/init-method-being-called-multiple-times-of-WrappingIterator-tt13506.html 

still seems like an order of magnitude off where I would expect memory problems - probably need to do a VM snapshot and see what's going on.

There might be some utility in creating a singleton instance containing a concurrent hashmaps or something so we only store one instance of the geometries for each jvm instance.

**Comment by chrisbennight** [comment]
@rfecher Okay, so I know you said not to do this, but I did it anyway :)
I think using a weak reference here for the caching should address the lifecycle problems you brought up (that I hadn't really thought all the way through) - unless I'm missing something once all iterators with a reference to the geometry go out of scope the geometry itself should clean itself up (in the next GC cycle).

Specifically check out the javadoc at http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Interners.html
for the Interners.newWeakInterner() method.   In testing the blow up at 29,000 above works fine @ 50k now.  

Here's the changes:
https://github.com/ngageoint/geowave/commit/f05e3da1f005c731eb3a361d76374a70f29a3f90#diff-f2bee951005d412569f3c9a737814cee

**Comment by chrisbennight** [comment]
@panrufio 
I think this might help with one of the issues you reported.  Should for the most part remove limits on query geometries (well, until the size of one instance of the geometry starts approaching a significant percentage of tabletserver heap - at that point you just need more memory if you want to filter on 2GB geometries :))

**Comment by rfecher** [comment]
fair enough, I like this solution much better than strong references with reference counters
