### ISSUE TITLE
Static initializer fails when run under per namespace classpaths

### ISSUE THREAD

**Issue by spohnan** [ngageoint/geowave#302]
**Description:** After setting up two GeoWave datastores in GeoServer using the new per namespace classpath configuration the second data store accessed will fail with the error below as the unguarded initializer will run again and attempt to re-register the factory.

**Setup:**

1. Configure two namespace classloaders in Accumulo
  * http://ngageoint.github.io/geowave/documentation.html#overview-5
1. Configure two GeoWave datastores with each one using a different namespace

**Stack Trace:**

exception while doing multi-scan 
	java.lang.Error: factory already defined
		at java.net.URL.setURLStreamHandlerFactory(URL.java:1104)
		at mil.nga.giat.geowave.vector.query.CqlQueryFilterIterator.<clinit>(CqlQueryFilterIterator.java:66)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
		at java.lang.Class.newInstance(Class.java:379)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:239)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:216)
		at org.apache.accumulo.core.iterators.IteratorUtil.loadIterators(IteratorUtil.java:194)
		at org.apache.accumulo.tserver.Tablet$ScanDataSource.createIterator(Tablet.java:1985)
		at org.apache.accumulo.tserver.Tablet$ScanDataSource.iterator(Tablet.java:1923)
		at org.apache.accumulo.core.iterators.system.SourceSwitchingIterator.seek(SourceSwitchingIterator.java:163)
		at org.apache.accumulo.tserver.Tablet.lookup(Tablet.java:1499)
		at org.apache.accumulo.tserver.Tablet.lookup(Tablet.java:1606)
		at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler$LookupTask.run(TabletServer.java:1119)
		at org.apache.accumulo.trace.instrument.TraceRunnable.run(TraceRunnable.java:47)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at org.apache.accumulo.trace.instrument.TraceRunnable.run(TraceRunnable.java:47)
		at org.apache.accumulo.core.util.LoggingRunnable.run(LoggingRunnable.java:34)
		at java.lang.Thread.run(Thread.java:745)

**Comment by chrisbennight** [comment]
So URL.setURLStreamHandlerFactory can only ever be called once per JVM instance (so multiple classloaders in an instance = multiple instance (of statics as well)).   The classloader isolation of accumulo (per namespace) does just this (by design).

We can't actually use a guard variable for this, since we would need a JVM level guard.  Instead I just handle the exception.  In the case of a conflict I check the type that's already been registered;  if it's what we want (FSUrlStreamHandlerFactory) then we are good to go;  we just had multiple static instances.   If it's a different type I throw an error.  We could unset/reset it (I do this in the unit tests), but I"m not sure how robust this is, and really we should find out what else on the classpath is registering a different factory.  So it's logged, and an error is thrown so we can track it down.  PR #303 should cover this.
