### ISSUE TITLE
GeowaveInputFormat query causes Out of Memory Error

### ISSUE THREAD

**Issue by jsnsts** [ngageoint/geowave#417]
Out of memory error occurred during a spatial and temporal query using GeowaveInputFormat.  The query was over a 1:50M shape file of the country of Brazil over a 6 month period.  The same query was successful when using a shape files of Italy.

The error:

java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:2694)
        at java.lang.String.<init>(String.java:203)
        at java.lang.StringBuilder.toString(StringBuilder.java:405)
        at com.google.common.io.GwtWorkarounds$6.toString(GwtWorkarounds.java:227)
        at com.google.common.io.BaseEncoding.encode(BaseEncoding.java:165)
        at com.google.common.io.BaseEncoding.encode(BaseEncoding.java:145)
        at mil.nga.giat.geowave.index.ByteArrayUtils.byteArrayToString(ByteArrayUtils.java:48)
        at mil.nga.giat.geowave.accumulo.query.AccumuloConstraintsQuery.addScanIteratorSettings(AccumuloConstraintsQuery.java:174)
        at mil.nga.giat.geowave.accumulo.query.AccumuloFilteredIndexQuery.query(AccumuloFilteredIndexQuery.java:94)
        at mil.nga.giat.geowave.accumulo.mapreduce.input.GeoWaveRecordReader.initialize(GeoWaveRecordReader.java:176)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:133)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:104)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:66)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by chrisbennight** [comment]
Hmm, have to dig in;  I'm assuming this isn't just the spark cluster running out of memory?  Do you know how much of the available cluster memory you are using for your object?  (i.e. is the number of features returned from Brazil > than that returned from the Italy query?)

My first guess might be was need another weak referenced interning here of the QueryFilterIterator
https://github.com/ngageoint/geowave/blob/master/extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloConstraintsQuery.java#L174
similar to this
https://github.com/ngageoint/geowave/blob/master/core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/filter/SpatialQueryFilter.java#L199 )

But the difference here is that the AccumuloConstraintsQuery lifecycle should result in anywhere near the number of instantions we get in the iterators - and this exception obviously isn't a tablet server exception.  

So if the spark cluster isn't completely full due to features ( @jsnsts - can you verify that ) we probably need to look at the AccumuloConstraintsQuery lifecycle  (assuming it's not a red herring - otherwise might need to profile the java heap memory usage)

**Comment by jsnsts** [comment]
This is the log output right before the error:

15/06/09 14:08:19 WARN TaskSetManager: Stage 1 contains a task of very large size (1803 KB). The maximum recommended task size is 100 KB.
15/06/09 14:08:19 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, ANY, 1846797 bytes)
15/06/09 14:08:19 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
15/06/09 14:08:20 INFO NewHadoopRDD: Input split: mil.nga.giat.geowave.accumulo.mapreduce.input.GeoWaveInputSplit@17a7fbb6
15/06/09 14:08:43 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)

The stack trace is a little different when run it with different geometries. The first line in the stack trace that is consistent is:

mil.nga.giat.geowave.accumulo.mapreduce.input.GeoWaveRecordReader.initialize(GeoWaveRecordReader.java:176)
