### ISSUE TITLE
DBScanMapReduceTest fails on Java 8

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#480]
Works fine on java 7

```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.532 sec <<< FAILURE!
testReducer(mil.nga.giat.geowave.analytic.mapreduce.dbscan.DBScanMapReduceTest)  Time elapsed: 0.051 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<3>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at mil.nga.giat.geowave.analytic.mapreduce.dbscan.DBScanMapReduceTest.testReducer(DBScanMapReduceTest.java:325)
```

**Comment by rwgdrummer** [comment]
Fix is complete.  Manage to squeeze out about ten orders magnitude of performance as well.
