### ISSUE TITLE
Random SpatialTemporalQueryIT.testTimeRangeAcrossBinsYear() failure in 0.9.1 branch

### ISSUE THREAD

**Issue by dcy2003** [ngageoint/geowave#625]
[Travis Build](https://travis-ci.org/ngageoint/geowave/jobs/108863973)
[Raw Log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/108863973/log.txt)

Stack Trace:

```
Tests run: 27, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,866.724 sec <<< FAILURE! - in mil.nga.giat.geowave.test.GeoWaveITSuite
testTimeRangeAcrossBinsYear(mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT)  Time elapsed: 0.688 sec  <<< FAILURE!
java.lang.AssertionError: Expected result count does not match actual result count for year expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.assertFidsMatchExpectation(SpatialTemporalQueryIT.java:616)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.testQueryGivenDateRange(SpatialTemporalQueryIT.java:606)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.testTimeRangeAcrossBins(SpatialTemporalQueryIT.java:704)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.testTimeRangeAcrossBinsYear(SpatialTemporalQueryIT.java:804)


Results :

Failed tests: 
  SpatialTemporalQueryIT.testTimeRangeAcrossBinsYear:804->testTimeRangeAcrossBins:704->testQueryGivenDateRange:606->assertFidsMatchExpectation:616 Expected result count does not match actual result count for year expected:<2> but was:<3>
```

**Comment by rfecher** [comment]
well, thats annoying...I'll try to investigate this a little more

**Comment by dcy2003** [comment]
Similar, but different failure:

```
Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,011.932 sec <<< FAILURE! - in mil.nga.giat.geowave.test.GeoWaveITSuite
testTimeRangeAcrossBinsMonth(mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT)  Time elapsed: 3.454 sec  <<< FAILURE!
java.lang.AssertionError: Expected result count does not match actual result count for month expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.assertFidsMatchExpectation(SpatialTemporalQueryIT.java:616)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.testQueryGivenDateRange(SpatialTemporalQueryIT.java:606)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.testTimeRangeAcrossBins(SpatialTemporalQueryIT.java:726)
	at mil.nga.giat.geowave.test.query.SpatialTemporalQueryIT.testTimeRangeAcrossBinsMonth(SpatialTemporalQueryIT.java:786)


Results :

Failed tests: 
  SpatialTemporalQueryIT.testTimeRangeAcrossBinsMonth:786->testTimeRangeAcrossBins:726->testQueryGivenDateRange:606->assertFidsMatchExpectation:616 Expected result count does not match actual result count for month expected:<2> but was:<3>

Tests run: 31, Failures: 1, Errors: 0, Skipped: 0
```

[Raw](https://s3.amazonaws.com/archive.travis-ci.org/jobs/109638754/log.txt)
[Travis](https://travis-ci.org/ngageoint/geowave/jobs/109638754)

**Comment by rwgdrummer** [comment]
Finally getting a grasp on this issue.
The test issues two queries: one through the API directly and one through Geotools API.  The Geotools API uses a  CQLFilter .  The CQLFilter is a distributed filter run on the tablet (one server in this case, but potential multiple threads).  The CQLFilter is some how causing a disruption where the 'first' expected feature is being excluded.  The filter, itself, is correct.  If you run the filter in the client rather than the server, everything works fine.  This means the constraint portions of the query are correct, and, in fact match in both issued queries--api and geotools.  I check to see if the filter is parsed correctly. It looked ok.
Since it is intermittent, I doubt is a timezone issue (the queries in question are filtering on date attributes).   A failure to decode automatically returns false without warning.  I put a log message in this position and did not see an error.  That is all I have at this moment.    I spent four to five  hours puzzling over this issue.
