### ISSUE TITLE
KMeansIT random failure

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#718]
testIngestAndQueryGeneralGpx(mil.nga.giat.geowave.test.mapreduce.GeoWaveKMeansIT)  Time elapsed: 385.52 sec  <<< FAILURE!
java.lang.AssertionError: 12788833-c4c4-4ad7-9e61-d3f68884ee39
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at mil.nga.giat.geowave.test.mapreduce.GeoWaveKMeansIT.countResults(GeoWaveKMeansIT.java:365)
	at mil.nga.giat.geowave.test.mapreduce.GeoWaveKMeansIT.runKPlusPlus(GeoWaveKMeansIT.java:227)
	at mil.nga.giat.geowave.test.mapreduce.GeoWaveKMeansIT.testIngestAndQueryGeneralGpx(GeoWaveKMeansIT.java:157)

Here's the log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/123993203/log.txt

**Comment by rfecher** [comment]
Haven't seen it since the original issue, doesn't seem to be an issue anymore
