### ISSUE TITLE
Change in behavior of AccumuloDataStatisticsStore.getDataStatistics Breaks GeoTrellis Integration

### ISSUE THREAD

**Issue by jamesmcclain** [ngageoint/geowave#914]
The GeoWave/GeoTrellis integration code that we have does not work with the most recent versions of GeoWave.  The last known-working version is `c127c16`.

The failure occurs on [this line](https://github.com/geotrellis/geotrellis/blob/master/geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveAttributeStore.scala#L133-L135), and produces an error of this form:

```
java.nio.BufferUnderflowException:
at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
at java.nio.ByteBuffer.get(ByteBuffer.java:715)
at mil.nga.giat.geowave.core.store.adapter.statistics.AbstractDataStatistics.binaryBuffer(AbstractDataStatistics.java:75)
at mil.nga.giat.geowave.core.geotime.store.statistics.BoundingBoxDataStatistics.fromBinary(BoundingBoxDataStatistics.java:95)
at mil.nga.giat.geowave.core.index.PersistenceUtils.fromBinary(PersistenceUtils.java:96)
at mil.nga.giat.geowave.datastore.accumulo.metadata.AbstractAccumuloPersistence.entryToValue(AbstractAccumuloPersistence.java:263)
at mil.nga.giat.geowave.datastore.accumulo.metadata.AccumuloDataStatisticsStore.entryToValue(AccumuloDataStatisticsStore.java:156)
at mil.nga.giat.geowave.datastore.accumulo.metadata.AccumuloDataStatisticsStore.entryToValue(AccumuloDataStatisticsStore.java:40)
at mil.nga.giat.geowave.datastore.accumulo.metadata.AbstractAccumuloPersistence.getObject(AbstractAccumuloPersistence.java:225)
at mil.nga.giat.geowave.datastore.accumulo.metadata.AccumuloDataStatisticsStore.getDataStatistics(AccumuloDataStatisticsStore.java:147)
...
```

**Comment by jamesmcclain** [comment]
This appears to have been fixed by locationtech/geotrellis#1933
